name: CI-CD-Pipeline-to-AWS-ElasticBeanstalk
env:
  EB_PACKAGE_S3_BUCKET_NAME : "lexpro-it-flusk-applications-packages"
  EB_APPLICATION_NAME       : "MyFlusk"
  EB_ENVIRONMENT_NAME       : "MyFlusk-env"
  DEPLOY_PACKAGE_NAME       : "flusk_app_${{ github.sha }}.zip"
  AWS_REGION_NAME           : "us-west-2"

on:  
  push:
    branches: master

jobs:
  my-ci-part:

    runs-on: ubuntu-latest

    steps:
    - name: Git clone our repo
      uses: actions/checkout@v1
      
      
    - name: Create ZIP deployment package
      run : zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
    
    - name: Configure my AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id    :  ${{ secrets.MY_AWS_ACCESS_KEY }}
        aws-secret-access-key:  ${{ secrets.MY_AWS_SECRET_KEY }}
        aws-region           :  ${{ env.AWS_REGION_NAME }}
    
    - name: Copy deployment package to S3 bucket
      run : aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME }}/
      
    - name: Print Happy message for CI finish
      run: echo "CI Pipeline part finished succesfully!"
      
    
     
